-- Seed: 90 curiosities + 10 house ads (Aside as initial sponsor).
-- English. Generated from scripts/curiosities.en.json. Inserts only when empty.

do $$
declare
  aside uuid;
begin
  if (select count(*) from curiosities) > 0 then
    return;
  end if;

  insert into sponsors (name, handle) values ('Aside', 'aside') returning id into aside;
  insert into campaigns (sponsor_id, starts_at, ends_at, status)
    values (aside, now() - interval '1 day', now() + interval '365 days', 'live');

  insert into curiosities (body, topic, difficulty, is_sponsored, sponsor_id, status, click_url, source_note) values
    ('The first computer "bug" was a real moth, taped into a logbook in 1947.', 'history', 'easy', false, null, 'live', null, 'seed-en'),
    ('HTTP 418 "I''m a teapot" is a real status code, from a 1998 April Fools RFC.', 'protocols', 'easy', false, null, 'live', null, 'seed-en'),
    ('Tony Hoare called inventing the null reference his "billion-dollar mistake."', 'languages', 'mid', false, null, 'live', null, 'seed-en'),
    ('The @ in email? Ray Tomlinson grabbed it in 1971 because the key was unused.', 'history', 'easy', false, null, 'live', null, 'seed-en'),
    ('Python is named after Monty Python — not the snake.', 'languages', 'easy', false, null, 'live', null, 'seed-en'),
    ('Linus Torvalds wrote the first working version of Git in about ten days, in 2005.', 'git', 'mid', false, null, 'live', null, 'seed-en'),
    ('Signed 32-bit Unix time runs out on Jan 19, 2038 — the Y2038 problem.', 'time', 'mid', false, null, 'live', null, 'seed-en'),
    ('The first webcam watched a coffee pot, so Cambridge staff wouldn''t find it empty.', 'history', 'easy', false, null, 'live', null, 'seed-en'),
    ('grep is named after the old ed command g/re/p — global / regex / print.', 'shell', 'mid', false, null, 'live', null, 'seed-en'),
    ('The placeholders "foo" and "bar" likely come from WWII-era slang "FUBAR."', 'trivia', 'easy', false, null, 'live', null, 'seed-en'),
    ('Ada Lovelace published the first algorithm meant for a machine — in 1843.', 'history', 'mid', false, null, 'live', null, 'seed-en'),
    ('Your whole 127.0.0.0/8 block — 16 million addresses — is loopback. You use one.', 'networking', 'mid', false, null, 'live', null, 'seed-en'),
    ('Git relied on SHA-1 until Google produced a real collision, "SHAttered," in 2017.', 'security', 'deep', false, null, 'live', null, 'seed-en'),
    ('A background "daemon" is named after Maxwell''s demon — not the evil kind.', 'trivia', 'mid', false, null, 'live', null, 'seed-en'),
    ('"Byte" was spelled with a y on purpose, so no one would confuse it with "bit."', 'trivia', 'mid', false, null, 'live', null, 'seed-en'),
    ('The Apollo 11 guidance computer landed on the Moon with about 4 KB of RAM.', 'history', 'mid', false, null, 'live', null, 'seed-en'),
    ('Margaret Hamilton coined "software engineering" while writing Apollo''s flight code.', 'history', 'mid', false, null, 'live', null, 'seed-en'),
    ('On paper tape you deleted a character by punching every hole — that''s why DEL is 127.', 'trivia', 'deep', false, null, 'live', null, 'seed-en'),
    ('Grace Hopper wrote the first compiler, the A-0, in 1952.', 'history', 'mid', false, null, 'live', null, 'seed-en'),
    ('"Computer" was originally a job title — a person who did calculations by hand.', 'history', 'easy', false, null, 'live', null, 'seed-en'),
    ('The first website is still online at info.cern.ch, barely changed since the early ''90s.', 'history', 'easy', false, null, 'live', null, 'seed-en'),
    ('Tim Berners-Lee''s first browser was also an editor — the web was meant to be writable.', 'history', 'mid', false, null, 'live', null, 'seed-en'),
    ('IBM''s first gigabyte drive (1980) weighed over 200 kg and cost a fortune.', 'history', 'mid', false, null, 'live', null, 'seed-en'),
    ('Douglas Engelbart demoed the mouse, hypertext, and video calls — back in 1968.', 'history', 'mid', false, null, 'live', null, 'seed-en'),
    ('QWERTY was arranged in the 1870s to keep typewriter bars from jamming.', 'trivia', 'easy', false, null, 'live', null, 'seed-en'),
    ('The word "robot" comes from a 1920 Czech play; "robota" means forced labor.', 'trivia', 'easy', false, null, 'live', null, 'seed-en'),
    ('"Bit" is short for "binary digit," a term coined back in 1947.', 'trivia', 'easy', false, null, 'live', null, 'seed-en'),
    ('Hedy Lamarr co-patented frequency hopping — an ancestor of Wi-Fi and Bluetooth.', 'history', 'mid', false, null, 'live', null, 'seed-en'),
    ('The first spam email was sent over ARPANET in 1978.', 'history', 'easy', false, null, 'live', null, 'seed-en'),
    ('The Morris Worm (1988) was one of the first internet worms — and the first CFAA case.', 'security', 'mid', false, null, 'live', null, 'seed-en'),
    ('PHP originally stood for "Personal Home Page."', 'languages', 'easy', false, null, 'live', null, 'seed-en'),
    ('Brendan Eich created JavaScript in about ten days, in 1995.', 'languages', 'mid', false, null, 'live', null, 'seed-en'),
    ('JavaScript is unrelated to Java — the name was pure marketing.', 'languages', 'easy', false, null, 'live', null, 'seed-en'),
    ('Unix was first written in assembly, then rewritten in C around 1973.', 'history', 'mid', false, null, 'live', null, 'seed-en'),
    ('C and Unix grew up together at Bell Labs, both shaped by Dennis Ritchie.', 'history', 'mid', false, null, 'live', null, 'seed-en'),
    ('"Hello, world" traces back to a Bell Labs tutorial from 1972.', 'history', 'easy', false, null, 'live', null, 'seed-en'),
    ('SQL was first called SEQUEL, until a trademark forced the rename.', 'languages', 'mid', false, null, 'live', null, 'seed-en'),
    ('GIF''s creator insists it''s pronounced "jif." The argument never ends.', 'trivia', 'easy', false, null, 'live', null, 'seed-en'),
    ('Wi-Fi doesn''t actually stand for anything — it''s just a brand name.', 'trivia', 'easy', false, null, 'live', null, 'seed-en'),
    ('ping was named after the sound of sonar, by its author in 1983.', 'networking', 'mid', false, null, 'live', null, 'seed-en'),
    ('"Spam" for junk messages comes straight from a Monty Python sketch.', 'trivia', 'easy', false, null, 'live', null, 'seed-en'),
    ('A TCP connection opens with a three-way handshake: SYN, SYN-ACK, ACK.', 'networking', 'mid', false, null, 'live', null, 'seed-en'),
    ('UDP makes no promises about delivery or order — that''s the whole point.', 'networking', 'mid', false, null, 'live', null, 'seed-en'),
    ('IPv4 has ~4.3 billion addresses, and we used them all up. Hence IPv6.', 'networking', 'mid', false, null, 'live', null, 'seed-en'),
    ('IPv6 has enough addresses to label every grain of sand many times over.', 'networking', 'easy', false, null, 'live', null, 'seed-en'),
    ('A MAC address''s first half identifies the hardware''s manufacturer.', 'networking', 'mid', false, null, 'live', null, 'seed-en'),
    ('HTTP 4xx means "your fault"; 5xx means "the server''s fault."', 'protocols', 'easy', false, null, 'live', null, 'seed-en'),
    ('traceroute works by deliberately letting packets expire one hop at a time.', 'networking', 'deep', false, null, 'live', null, 'seed-en'),
    ('sudo is just short for "superuser do."', 'shell', 'easy', false, null, 'live', null, 'seed-en'),
    ('awk is named after its authors: Aho, Weinberger, and Kernighan.', 'shell', 'mid', false, null, 'live', null, 'seed-en'),
    ('Anything written to /dev/null vanishes — it''s the system''s bit bucket.', 'shell', 'easy', false, null, 'live', null, 'seed-en'),
    ('In Unix, almost everything is a file — even devices and network sockets.', 'shell', 'mid', false, null, 'live', null, 'seed-en'),
    ('The ~ for "home" survives from a terminal where Home and ~ shared one key.', 'trivia', 'deep', false, null, 'live', null, 'seed-en'),
    ('vi was written by Bill Joy in 1976; "how do I quit vim" is eternal.', 'shell', 'easy', false, null, 'live', null, 'seed-en'),
    ('Ctrl+C sends SIGINT — and the keystroke itself is ASCII character 3.', 'shell', 'mid', false, null, 'live', null, 'seed-en'),
    ('cron takes its name from the Greek word for time, "chronos."', 'shell', 'easy', false, null, 'live', null, 'seed-en'),
    ('tar means "tape archive" — it''s older than the disks you back up with it.', 'shell', 'mid', false, null, 'live', null, 'seed-en'),
    ('A "tty" is a teletypewriter; terminals are named after machines they replaced.', 'trivia', 'mid', false, null, 'live', null, 'seed-en'),
    ('The root user is simply UID 0 — that number is what makes it all-powerful.', 'shell', 'mid', false, null, 'live', null, 'seed-en'),
    ('Lisp (1958) is the second-oldest language still in use, after Fortran.', 'languages', 'mid', false, null, 'live', null, 'seed-en'),
    ('0.1 + 0.2 doesn''t equal 0.3 in most languages — blame binary floating point.', 'languages', 'mid', false, null, 'live', null, 'seed-en'),
    ('Booleans are named after George Boole, a mathematician born in 1815.', 'trivia', 'easy', false, null, 'live', null, 'seed-en'),
    ('"Turing complete" traces to Alan Turing''s imaginary machine from 1936.', 'languages', 'mid', false, null, 'live', null, 'seed-en'),
    ('Regular expressions grew out of Stephen Kleene''s 1950s math on languages.', 'languages', 'deep', false, null, 'live', null, 'seed-en'),
    ('The semaphore in concurrency was named by Dijkstra, after railway signals.', 'languages', 'mid', false, null, 'live', null, 'seed-en'),
    ('Dijkstra designed his famous shortest-path algorithm in about 20 minutes.', 'languages', 'mid', false, null, 'live', null, 'seed-en'),
    ('Quicksort was invented by Tony Hoare around 1959.', 'languages', 'mid', false, null, 'live', null, 'seed-en'),
    ('The first antivirus, "Reaper," was built to delete an earlier program, "Creeper."', 'security', 'mid', false, null, 'live', null, 'seed-en'),
    ('Public-key crypto was secretly invented at GCHQ years before it went public.', 'security', 'deep', false, null, 'live', null, 'seed-en'),
    ('Turing''s team at Bletchley Park cracked Enigma, helping shorten WWII.', 'history', 'mid', false, null, 'live', null, 'seed-en'),
    ('Salting passwords means identical passwords still hash to different values.', 'security', 'mid', false, null, 'live', null, 'seed-en'),
    ('For years, the world''s most common password was literally "123456."', 'security', 'easy', false, null, 'live', null, 'seed-en'),
    ('Tux the Linux penguin exists because Linus likes penguins — one even bit him.', 'trivia', 'easy', false, null, 'live', null, 'seed-en'),
    ('Moore''s Law was a 1965 observation, not a law of physics.', 'trivia', 'mid', false, null, 'live', null, 'seed-en'),
    ('"Google" is a misspelling of "googol" — the number 10 to the 100th.', 'trivia', 'easy', false, null, 'live', null, 'seed-en'),
    ('The QR code was invented in 1994 to track car parts.', 'trivia', 'easy', false, null, 'live', null, 'seed-en'),
    ('Bluetooth is named after a 10th-century Danish king; its logo is his runic initials.', 'trivia', 'mid', false, null, 'live', null, 'seed-en'),
    ('The power symbol is a 1 inside a 0 — binary for on and off.', 'trivia', 'easy', false, null, 'live', null, 'seed-en'),
    ('The Y2K bug came from storing years as two digits to save scarce memory.', 'history', 'mid', false, null, 'live', null, 'seed-en'),
    ('The "404 = a room at CERN" story is a myth; it''s just an HTTP status code.', 'protocols', 'easy', false, null, 'live', null, 'seed-en'),
    ('Cookies are named after "magic cookies," a Unix idea older than the web.', 'protocols', 'mid', false, null, 'live', null, 'seed-en'),
    ('Ports only go up to 65535 because the port field is 16 bits wide.', 'networking', 'mid', false, null, 'live', null, 'seed-en'),
    ('On Unix, ports below 1024 need root — a rule from the early days of the net.', 'networking', 'mid', false, null, 'live', null, 'seed-en'),
    ('The bell character (\a) can still make a terminal beep out loud.', 'shell', 'easy', false, null, 'live', null, 'seed-en'),
    ('A 502 error means the gateway''s upstream failed — not your front end.', 'networking', 'mid', false, null, 'live', null, 'seed-en'),
    ('RAM is "volatile" because it forgets everything the moment power is cut.', 'trivia', 'easy', false, null, 'live', null, 'seed-en'),
    ('Before "at," the @ symbol had a dozen quirky names across languages.', 'trivia', 'easy', false, null, 'live', null, 'seed-en'),
    ('Kernighan and Ritchie''s "K&R" C book (1978) still shapes how we write code.', 'history', 'mid', false, null, 'live', null, 'seed-en'),
    ('Hexadecimal needs 16 symbols, so it borrows A–F after 0–9.', 'languages', 'easy', false, null, 'live', null, 'seed-en'),
    ('There are two hard things in CS: cache invalidation, naming, and off-by-one errors.', 'trivia', 'easy', false, null, 'live', null, 'seed-en'),
    ('Aside is open source and privacy-first — it never reads your code.', 'sponsor', 'easy', true, aside, 'live', 'https://aside-melissas-projects-6a8130ee.vercel.app/', 'aside-house-ad'),
    ('Enjoying these? Aside drops a fresh dev curiosity into every wait-state.', 'sponsor', 'easy', true, aside, 'live', 'https://aside-melissas-projects-6a8130ee.vercel.app/', 'aside-house-ad'),
    ('Aside runs locally and works offline — the network never blocks your terminal.', 'sponsor', 'easy', true, aside, 'live', 'https://aside-melissas-projects-6a8130ee.vercel.app/', 'aside-house-ad'),
    ('Aside reads two harmless fields and throws the rest away. Run `aside about`.', 'sponsor', 'easy', true, aside, 'live', 'https://aside-melissas-projects-6a8130ee.vercel.app/about', 'aside-house-ad'),
    ('Like a fact? Every Aside line is signed and ready to screenshot.', 'sponsor', 'easy', true, aside, 'live', 'https://aside-melissas-projects-6a8130ee.vercel.app/', 'aside-house-ad'),
    ('Aside never touches your files, paths, or prompts — and the code proves it.', 'sponsor', 'easy', true, aside, 'live', 'https://aside-melissas-projects-6a8130ee.vercel.app/about', 'aside-house-ad'),
    ('Want your message in dev''s most-watched line? Sponsor Aside.', 'sponsor', 'easy', true, aside, 'live', 'https://aside-melissas-projects-6a8130ee.vercel.app/sponsor', 'aside-house-ad'),
    ('One curious line while the AI thinks. Aside, MIT-licensed.', 'sponsor', 'easy', true, aside, 'live', 'https://aside-melissas-projects-6a8130ee.vercel.app/', 'aside-house-ad'),
    ('New here? npm i -g @aside/cli && aside install.', 'sponsor', 'easy', true, aside, 'live', 'https://aside-melissas-projects-6a8130ee.vercel.app/', 'aside-house-ad'),
    ('Aside turns idle wait-states into something worth reading.', 'sponsor', 'easy', true, aside, 'live', 'https://aside-melissas-projects-6a8130ee.vercel.app/', 'aside-house-ad');
end $$;
